platform :ios, '8.0'

target 'MapExample' do

pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'

pod 'GoogleMaps'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

end