const Graph = require('node-dijkstra');
const difficultRoute = new Graph();
difficultRoute.addNode("AA", { AB: 1, BA: 1 })
difficultRoute.addNode("AB", { AA: 1, AC: 1, BB: 1 })
difficultRoute.addNode("AC", { AB: 1, AD: 1, BB: 1 })
difficultRoute.addNode("AD", { AC: 1, BE: 1, HB: 1 })
difficultRoute.addNode("AE", { AL: 1, HA: 1, HC: 1 })
difficultRoute.addNode("AF", { AG: 1, GY: 1 })
difficultRoute.addNode("AG", { AF: 1, AH: 1 })
difficultRoute.addNode("AH", { AG: 1, AI: 1, AP: 1 })
difficultRoute.addNode("AI", { AH: 1, AJ: 1 })
difficultRoute.addNode("AJ", { AI: 1, AK: 1, AO: 1 })
difficultRoute.addNode("AK", { AJ: 1, AR: 1, AZ: 1 })
difficultRoute.addNode("AL", { AE: 1, AM: 1, AS: 1 })
difficultRoute.addNode("AM", { AN: 1, AL: 1 })
difficultRoute.addNode("AN", { AM: 1, AO: 1, AQ: 1 })
difficultRoute.addNode("AO", { AJ: 1, AN: 1, AP: 1, AR: 1 })
difficultRoute.addNode("AP", { AH: 1, AO: 1 })
difficultRoute.addNode("AQ", { AN: 1, AR: 1, AS: 1 })
difficultRoute.addNode("AR", { AK: 1, AO: 1, AQ: 1, AU: 1 })
difficultRoute.addNode("AS", { AL: 1, AQ: 1, AT: 1 })
difficultRoute.addNode("AT", { AS: 1, AU: 1, BL: 1 })
difficultRoute.addNode("AU", { AR: 1, AT: 1, AV: 1 })
difficultRoute.addNode("AV", { AU: 1, CB: 1, CE: 1, CD: 100 })
difficultRoute.addNode("AW", { AX: 1, CE: 1, HE: 1 })
difficultRoute.addNode("AX", { AW: 1, AY: 1 })
difficultRoute.addNode("AY", { AX: 1, CN: 1, HH: 1 })
difficultRoute.addNode("AZ", { AK: 1, CO: 1, HG: 1 })
difficultRoute.addNode("BA", { AA: 1, BB: 1, BC: 1, DA: 100 })
difficultRoute.addNode("BB", { AB: 1, AC: 1, BA: 1 })
difficultRoute.addNode("BC", { BA: 1, BD: 1, BN: 1 })
difficultRoute.addNode("BD", { BC: 1, BE: 1, BF: 1 })
difficultRoute.addNode("BE", { AD: 1, BD: 1, BF: 1 })
difficultRoute.addNode("BF", { BD: 1, BE: 1, BG: 1 })
difficultRoute.addNode("BG", { BF: 1, BH: 1, BQ: 1 })
difficultRoute.addNode("BH", { BG: 1, BI: 1, BM: 100 })
difficultRoute.addNode("BI", { BH: 1, BJ: 1, BT: 1 })
difficultRoute.addNode("BJ", { BI: 1, BK: 1, BU: 100 })
difficultRoute.addNode("BK", { BJ: 1, BL: 1, BM: 1 })
difficultRoute.addNode("BL", { BK: 1, BM: 100, BW: 100, BY: 1 })
difficultRoute.addNode("BM", { BH: 100, BK: 1, BL: 100 })
difficultRoute.addNode("BN", { BC: 1, BO: 1, DA: 1 })
difficultRoute.addNode("BO", { BN: 1, BP: 1, DD: 100 })
difficultRoute.addNode("BP", { BO: 1, BQ: 1, DH: 100 })
difficultRoute.addNode("BQ", { BG: 1, BP: 1, BR: 1 })
difficultRoute.addNode("BR", { BQ: 1, BS: 1, DJ: 100 })
difficultRoute.addNode("BS", { BR: 1, BT: 100, BU: 1, DK: 100 })
difficultRoute.addNode("BT", { BI: 1, BS: 100 })
difficultRoute.addNode("BU", { BJ: 100, BS: 1, BV: 1 })
difficultRoute.addNode("BV", { BU: 1, BW: 1, DM: 100 })
difficultRoute.addNode("BW", { BL: 100, BV: 1, BX: 1, EG: 100 })
difficultRoute.addNode("BX", { BW: 1, BY: 10000, BZ: 1, EI: 100 })
difficultRoute.addNode("BY", { BL: 1, BX: 10000, CA: 1 })
difficultRoute.addNode("BZ", { BX: 1, CA: 100, CC: 1, EM: 100 })
difficultRoute.addNode("CA", { BY: 1, BZ: 100, CB: 1 })
difficultRoute.addNode("CB", { AV: 1, CA: 1, CC: 100 })
difficultRoute.addNode("CC", { BZ: 1, CB: 100, CD: 1, EN: 100 })
difficultRoute.addNode("CD", { AV: 100, CC: 1, CF: 1, EW: 100 })
difficultRoute.addNode("CE", { AV: 1, AW: 1, CF: 100, CH: 100 })
difficultRoute.addNode("CF", { CD: 1, CE: 100, CG: 1, EU: 100 })
difficultRoute.addNode("CG", { CF: 1, CH: 100, CI: 1, ET: 100 })
difficultRoute.addNode("CH", { CE: 100, CG: 100, CJ: 100 })
difficultRoute.addNode("CI", { CG: 1, CJ: 1, ES: 100 })
difficultRoute.addNode("CJ", { CH: 100, CI: 1, CK: 1 })
difficultRoute.addNode("CK", { CJ: 1, CL: 100, CQ: 100 })
difficultRoute.addNode("CL", { CK: 10000, CM: 1, HD: 1 })
difficultRoute.addNode("CM", { CL: 1, CP: 100 })
difficultRoute.addNode("CN", { AY: 1, CP: 1, CO: 1 })
difficultRoute.addNode("CO", { AZ: 1, CN: 1, GX: 3 })
difficultRoute.addNode("CP", { CM: 100, CN: 1, GX: 1 })
difficultRoute.addNode("CQ", { CK: 100, CR: 100, ES: 1 })
difficultRoute.addNode("CR", { CQ: 100, CS: 100 })
difficultRoute.addNode("CS", { CR: 100, CT: 100, CZ: 1 })
difficultRoute.addNode("CT", { CS: 100, CU: 100, CY: 1 })
difficultRoute.addNode("CU", { CT: 100, CV: 1, CX: 1, FE: 1 })
difficultRoute.addNode("CV", { CU: 1, CW: 1, FC: 1 })
difficultRoute.addNode("CW", { CV: 1, CX: 1, EZ: 1 })
difficultRoute.addNode("CX", { CU: 1, CW: 1, CY: 1 })
difficultRoute.addNode("CY", { CT: 1, CX: 1, CZ: 1 })
difficultRoute.addNode("CZ", { CS: 1, CY: 1, FB: 1 })
difficultRoute.addNode("DA", { BA: 100, BN: 1, DB: 1 })
difficultRoute.addNode("DB", { DA: 1, DC: 1, DE: 1 })
difficultRoute.addNode("DC", { DB: 1, GA: 100 })
difficultRoute.addNode("DD", { BO: 100, DE: 1, DH: 1 })
difficultRoute.addNode("DE", { DB: 1, DD: 1, DF: 1 })
difficultRoute.addNode("DF", { DE: 1, DG: 1 })
difficultRoute.addNode("DG", { DF: 1, DP: 1 })
difficultRoute.addNode("DH", { BP: 100, DD: 1, DI: 1 })
difficultRoute.addNode("DI", { DH: 1, DJ: 1, DR: 1 })
difficultRoute.addNode("DJ", { BR: 100, DI: 1, DK: 1 })
difficultRoute.addNode("DK", { BS: 100, DJ: 1, DL: 1, DS: 1 })
difficultRoute.addNode("DL", { DK: 1, DM: 1, DU: 1 })
difficultRoute.addNode("DM", { BY: 100, DL: 1, DN: 1 })
difficultRoute.addNode("DN", { DM: 1, DO: 1, DV: 1 })
difficultRoute.addNode("DO", { DN: 1, EB: 1, EG: 1 })
difficultRoute.addNode("DP", { DG: 1, DQ: 1, GB: 1 })
difficultRoute.addNode("DQ", { DP: 1, DR: 1, DW: 1 })
difficultRoute.addNode("DR", { DI: 1, DQ: 1, DT: 1 })
difficultRoute.addNode("DS", { DK: 1, DT: 1 })
difficultRoute.addNode("DT", { DR: 1, DS: 1, DU: 1, DX: 1 })
difficultRoute.addNode("DU", { DL: 1, DT: 1, DV: 1 })
difficultRoute.addNode("DV", { DN: 1, DU: 1, DY: 1 })
difficultRoute.addNode("DW", { DQ: 1, DX: 1, GC: 1 })
difficultRoute.addNode("DX", { DT: 1, DW: 1, DY: 1, GW: 1 })
difficultRoute.addNode("DY", { DV: 1, DX: 1, DZ: 1 })
difficultRoute.addNode("DZ", { DY: 1, EA: 1, GW: 1 })
difficultRoute.addNode("EA", { DZ: 1, EB: 100, EC: 1 })
difficultRoute.addNode("EB", { DO: 1, EA: 100 })
difficultRoute.addNode("EC", { EA: 1, ED: 1, GT: 100 })
difficultRoute.addNode("ED", { EC: 1, EE: 100, GU: 100 })
difficultRoute.addNode("EE", { ED: 100, EF: 100, EJ: 1 })
difficultRoute.addNode("EF", { EE: 100, EH: 1 })
difficultRoute.addNode("EG", { BW: 100, DO: 1, EH: 1 })
difficultRoute.addNode("EH", { EF: 1, EG: 1, EI: 1 })
difficultRoute.addNode("EI", { BX: 100, EH: 1, EJ: 100, EK: 1 })
difficultRoute.addNode("EJ", { EE: 1, EI: 100, EL: 1 })
difficultRoute.addNode("EK", { EI: 1, EL: 100, EM: 1 })
difficultRoute.addNode("EL", { EJ: 1, EK: 100, EO: 100, GV: 100 })
difficultRoute.addNode("EM", { BZ: 100, EK: 1, EN: 1 })
difficultRoute.addNode("EN", { CC: 100, EM: 1, EV: 1 })
difficultRoute.addNode("EO", { EL: 100, EP: 1, EV: 1 })
difficultRoute.addNode("EP", { EO: 1, EQ: 1 })
difficultRoute.addNode("EQ", { EP: 1, ER: 1 })
difficultRoute.addNode("ER", { EQ: 1, ES: 1 })
difficultRoute.addNode("ES", { CI: 100, CQ: 1, ER: 1, ET: 1 })
difficultRoute.addNode("ET", { CG: 100, ES: 1, EU: 1 })
difficultRoute.addNode("EU", { CF: 100, ET: 1, EW: 1 })
difficultRoute.addNode("EV", { EN: 1, EO: 1, EW: 1 })
difficultRoute.addNode("EW", { CD: 100, EU: 1, EV: 1 })
difficultRoute.addNode("EX", { EY: 1, FL: 1, FS: 1 })
difficultRoute.addNode("EY", { EX: 1, FA: 1, FB: 1 })
difficultRoute.addNode("EZ", { CW: 1, FA: 1, FB: 1 })
difficultRoute.addNode("FA", { EY: 1, EZ: 1, FG: 1 })
difficultRoute.addNode("FB", { CZ: 1, EY: 1, EZ: 1 })
difficultRoute.addNode("FC", { CV: 1, FD: 1, FF: 1 })
difficultRoute.addNode("FD", { FC: 1, FE: 1 })
difficultRoute.addNode("FE", { CU: 1, FD: 1 })
difficultRoute.addNode("FF", { FC: 1, FG: 1, FI: 1 })
difficultRoute.addNode("FG", { FA: 1, FF: 1, FH: 1, FL: 1 })
difficultRoute.addNode("FH", { FG: 1, FI: 1, FK: 1 })
difficultRoute.addNode("FI", { FF: 1, FH: 1, FJ: 1 })
difficultRoute.addNode("FJ", { FI: 1, FK: 1, FM: 1 })
difficultRoute.addNode("FK", { FH: 1, FJ: 1, FL: 1 })
difficultRoute.addNode("FL", { EX: 1, FG: 1, FK: 1, FR: 1 })
difficultRoute.addNode("FM", { FJ: 1, FN: 1, FP: 1 })
difficultRoute.addNode("FN", { FM: 1, FO: 1 })
difficultRoute.addNode("FO", { FN: 1, FP: 1, FQ: 1, FV: 1, FY: 1 })
difficultRoute.addNode("FP", { FM: 1, FO: 1, GR: 1 })
difficultRoute.addNode("FQ", { FO: 1, FR: 1, FU: 1 })
difficultRoute.addNode("FR", { FL: 1, FQ: 1, FS: 1 })
difficultRoute.addNode("FS", { EX: 1, FR: 1, FT: 1 })
difficultRoute.addNode("FT", { FS: 1, FU: 100, GV: 100 })
difficultRoute.addNode("FU", { FQ: 1, FT: 100, FW: 1 })
difficultRoute.addNode("FV", { FO: 1, FW: 100 })
difficultRoute.addNode("FW", { FU: 1, FV: 100, FX: 1, GV: 100 })
difficultRoute.addNode("FX", { FW: 1, FY: 1, GS: 1 })
difficultRoute.addNode("FY", { FO: 1, FX: 1, FZ: 1 })
difficultRoute.addNode("FZ", { FY: 1, GO: 1, GQ: 1 })
difficultRoute.addNode("GA", { DC: 100, GB: 1 })
difficultRoute.addNode("GB", { DP: 1, GC: 1 })
difficultRoute.addNode("GC", { DW: 1, GB: 1, GD: 1 })
difficultRoute.addNode("GD", { GC: 1, GE: 10000, GW: 1 })
difficultRoute.addNode("GE", { GD: 10000, GF: 1 })
difficultRoute.addNode("GF", { GE: 1, GH: 100, GG: 1 })
difficultRoute.addNode("GG", { GF: 1, GI: 1, GJ: 1 })
difficultRoute.addNode("GH", { GF: 100, GI: 1, GW: 100 })
difficultRoute.addNode("GI", { GG: 1, GH: 1, HF: 1 })
difficultRoute.addNode("GJ", { GG: 1, GK: 1, GL: 1 })
difficultRoute.addNode("GK", { GJ: 1, GL: 1, GM: 1, HF: 1 })
difficultRoute.addNode("GL", { GJ: 1, GK: 1, GP: 1 })
difficultRoute.addNode("GM", { GK: 1, GN: 1 })
difficultRoute.addNode("GN", { GM: 1, GO: 1, GS: 100 })
difficultRoute.addNode("GO", { FZ: 1, GN: 1, GP: 1 })
difficultRoute.addNode("GP", { GL: 1, GO: 1, GQ: 1 })
difficultRoute.addNode("GQ", { FZ: 1, GP: 1, GR: 1 })
difficultRoute.addNode("GR", { FP: 1, GQ: 1 })
difficultRoute.addNode("GS", { FX: 1, GN: 100, GT: 100 })
difficultRoute.addNode("GT", { EC: 100, GS: 100, GU: 100 })
difficultRoute.addNode("GU", { ED: 100, GT: 100, GV: 100 })
difficultRoute.addNode("GV", { EL: 100, FT: 100, FW: 100, GU: 100 })
difficultRoute.addNode("GW", { DX: 1, DZ: 1, GD: 1, GH: 10000 })
difficultRoute.addNode("GX", { CO: 3, CP: 1 })
difficultRoute.addNode("GY", { AF: 1, GZ: 1 })
difficultRoute.addNode("GZ", { GY: 1, HC: 1 })
difficultRoute.addNode("HA", { AE: 1, HB: 1 })
difficultRoute.addNode("HB", { HA: 1, AD: 1 })
difficultRoute.addNode("HC", { GZ: 1, AE: 1 })
difficultRoute.addNode("HD", { CL: 1, HE: 1 })
difficultRoute.addNode("HE", { AW: 1, HD: 1 })
difficultRoute.addNode("HF", { GI: 1, GK: 1 })
difficultRoute.addNode("HG", { AZ: 1, HH: 1 })
difficultRoute.addNode("HH", { HG: 1, AY: 1 })

export {difficultRoute};