const Graph = require('node-dijkstra');
const easyRoute = new Graph();
easyRoute.addNode("AA", { AB: 1, AF: 1, BA: 1 })
easyRoute.addNode("AB", { AA: 1, AC: 1, BB: 10 })
easyRoute.addNode("AC", { AB: 1, AD: 1, BB: 10 })
easyRoute.addNode("AD", { AC: 1, AE: 1, BE: 1 })
easyRoute.addNode("AE", { AD: 1, AF: 1, AL: 1 })
easyRoute.addNode("AF", { AA: 1, AE: 1, AG: 1 })
easyRoute.addNode("AG", { AF: 1, AH: 10 })
easyRoute.addNode("AH", { AG: 10, AI: 10, AP: 10 })
easyRoute.addNode("AI", { AH: 10, AJ: 1 })
easyRoute.addNode("AJ", { AI: 1, AK: 1, AO: 1 })
easyRoute.addNode("AK", { AJ: 1, AR: 1, AZ: 1 })
easyRoute.addNode("AL", { AE: 1, AM: 1, AS: 1 })
easyRoute.addNode("AM", { AN: 1, AL: 1 })
easyRoute.addNode("AN", { AM: 1, AO: 10, AQ: 1 })
easyRoute.addNode("AO", { AJ: 1, AN: 10, AP: 1, AR: 1 })
easyRoute.addNode("AP", { AH: 10, AO: 1 })
easyRoute.addNode("AQ", { AN: 1, AR: 1, AS: 1 })
easyRoute.addNode("AR", { AK: 1, AO: 1, AQ: 1, AU: 1 })
easyRoute.addNode("AS", { AL: 1, AQ: 1, AT: 1 })
easyRoute.addNode("AT", { AS: 1, AU: 1, BL: 1 })
easyRoute.addNode("AU", { AR: 1, AT: 1, AV: 10 })
easyRoute.addNode("AV", { AU: 10, CB: 1, CE: 1, CD: 100 })
easyRoute.addNode("AW", { AX: 10, CE: 1, CL: 1 })
easyRoute.addNode("AX", { AW: 10, AY: 1 })
easyRoute.addNode("AY", { AX: 1, AZ: 1, CN: 1 })
easyRoute.addNode("AZ", { AK: 1, AY: 1, CO: 1 })
easyRoute.addNode("BA", { AA: 1, BB: 10, BC: 1, DA: 100 })
easyRoute.addNode("BB", { AB: 10, AC: 10, BA: 10 })
easyRoute.addNode("BC", { BA: 1, BD: 10, BN: 10 })
easyRoute.addNode("BD", { BC: 10, BE: 1, BF: 1 })
easyRoute.addNode("BE", { AD: 1, BD: 1, BF: 1 })
easyRoute.addNode("BF", { BD: 1, BE: 1, BG: 1 })
easyRoute.addNode("BG", { BF: 1, BH: 1, BQ: 1 })
easyRoute.addNode("BH", { BG: 1, BI: 1, BM: 100 })
easyRoute.addNode("BI", { BH: 1, BJ: 1, BT: 10 })
easyRoute.addNode("BJ", { BI: 1, BK: 10, BU: 100 })
easyRoute.addNode("BK", { BJ: 10, BL: 10, BM: 1 })
easyRoute.addNode("BL", { BK: 10, BM: 100, BW: 100, BY: 1 })
easyRoute.addNode("BM", { BH: 100, BK: 1, BL: 100 })
easyRoute.addNode("BN", { BC: 10, BO: 1, DA: 10 })
easyRoute.addNode("BO", { BN: 1, BP: 1, DD: 100 })
easyRoute.addNode("BP", { BO: 1, BQ: 1, DH: 100 })
easyRoute.addNode("BQ", { BG: 1, BP: 1, BR: 1 })
easyRoute.addNode("BR", { BQ: 1, BS: 1, DJ: 100 })
easyRoute.addNode("BS", { BR: 1, BT: 100, BU: 1, DK: 100 })
easyRoute.addNode("BT", { BI: 10, BS: 100 })
easyRoute.addNode("BU", { BJ: 100, BS: 1, BV: 1 })
easyRoute.addNode("BV", { BU: 1, BW: 1, DM: 100 })
easyRoute.addNode("BW", { BL: 100, BV: 1, BX: 1, EG: 100 })
easyRoute.addNode("BX", { BW: 1, BY: 1000, BZ: 1, EI: 100 })
easyRoute.addNode("BY", { BL: 1, BX: 1000, CA: 1 })
easyRoute.addNode("BZ", { BX: 1, CA: 100, CC: 1, EM: 100 })
easyRoute.addNode("CA", { BY: 1, BZ: 100, CB: 1 })
easyRoute.addNode("CB", { AV: 1, CA: 1, CC: 100 })
easyRoute.addNode("CC", { BZ: 1, CB: 100, CD: 1, EN: 100 })
easyRoute.addNode("CD", { AV: 100, CC: 1, CF: 1, EW: 100 })
easyRoute.addNode("CE", { AV: 1, AW: 1, CF: 100, CH: 100 })
easyRoute.addNode("CF", { CD: 1, CE: 100, CG: 1, EU: 100 })
easyRoute.addNode("CG", { CF: 1, CH: 100, CI: 1, ET: 100 })
easyRoute.addNode("CH", { CE: 100, CG: 100, CJ: 100 })
easyRoute.addNode("CI", { CG: 1, CJ: 1, ES: 100 })
easyRoute.addNode("CJ", { CH: 100, CI: 1, CK: 1 })
easyRoute.addNode("CK", { CJ: 1, CL: 100, CQ: 100 })
easyRoute.addNode("CL", { AW: 1, CK: 100, CM: 10 })
easyRoute.addNode("CM", { CL: 10, CP: 100 })
easyRoute.addNode("CN", { AY: 1, CP: 1 })
easyRoute.addNode("CO", { AZ: 1, CN: 10 })
easyRoute.addNode("CP", { CM: 100, CN: 1 })
easyRoute.addNode("CQ", { CK: 100, CR: 100, ES: 1 })
easyRoute.addNode("CR", { CQ: 100, CS: 100 })
easyRoute.addNode("CS", { CR: 100, CT: 100, CZ: 10 })
easyRoute.addNode("CT", { CS: 100, CU: 100, CY: 1 })
easyRoute.addNode("CU", { CT: 100, CV: 1, CX: 1, FE: 1 })
easyRoute.addNode("CV", { CU: 1, CW: 1, FC: 1 })
easyRoute.addNode("CW", { CV: 1, CX: 1, EZ: 1 })
easyRoute.addNode("CX", { CU: 1, CW: 1, CY: 1 })
easyRoute.addNode("CY", { CT: 1, CX: 1, CZ: 1 })
easyRoute.addNode("CZ", { CS: 10, CY: 1, FB: 1 })
easyRoute.addNode("DA", { BA: 100, BN: 10, DB: 10 })
easyRoute.addNode("DB", { DA: 10, DC: 10, DE: 1 })
easyRoute.addNode("DC", { DB: 10, GA: 100 })
easyRoute.addNode("DD", { BO: 100, DE: 1, DH: 1 })
easyRoute.addNode("DE", { DB: 1, DD: 1, DF: 10 })
easyRoute.addNode("DF", { DE: 10, DG: 1 })
easyRoute.addNode("DG", { DF: 1, DP: 1 })
easyRoute.addNode("DH", { BP: 100, DD: 1, DI: 1 })
easyRoute.addNode("DI", { DH: 1, DJ: 1, DR: 1 })
easyRoute.addNode("DJ", { BR: 100, DI: 1, DK: 1 })
easyRoute.addNode("DK", { BS: 100, DJ: 1, DL: 1, DS: 1 })
easyRoute.addNode("DL", { DK: 1, DM: 1, DU: 1 })
easyRoute.addNode("DM", { BY: 100, DL: 1, DN: 1 })
easyRoute.addNode("DN", { DM: 1, DO: 1, DV: 1 })
easyRoute.addNode("DO", { DN: 1, EB: 10, EG: 1 })
easyRoute.addNode("DP", { DG: 1, DQ: 1, GB: 10 })
easyRoute.addNode("DQ", { DP: 1, DR: 1, DW: 1 })
easyRoute.addNode("DR", { DI: 1, DQ: 1, DT: 1 })
easyRoute.addNode("DS", { DK: 1, DT: 10 })
easyRoute.addNode("DT", { DR: 1, DS: 10, DU: 1, DX: 1 })
easyRoute.addNode("DU", { DL: 1, DT: 1, DV: 1 })
easyRoute.addNode("DV", { DN: 1, DU: 1, DY: 1 })
easyRoute.addNode("DW", { DQ: 1, DX: 1, GC: 1 })
easyRoute.addNode("DX", { DT: 1, DW: 1, DY: 1, GW: 10 })
easyRoute.addNode("DY", { DV: 1, DX: 1, DZ: 10 })
easyRoute.addNode("DZ", { DY: 10, EA: 10, GW: 1 })
easyRoute.addNode("EA", { DZ: 10, EB: 100, EC: 10 })
easyRoute.addNode("EB", { DO: 10, EA: 100 })
easyRoute.addNode("EC", { EA: 10, ED: 10, GT: 100 })
easyRoute.addNode("ED", { EC: 10, EE: 100, GU: 100 })
easyRoute.addNode("EE", { ED: 100, EF: 100, EJ: 10 })
easyRoute.addNode("EF", { EE: 100, EH: 10 })
easyRoute.addNode("EG", { BW: 100, DO: 1, EH: 1 })
easyRoute.addNode("EH", { EF: 10, EG: 1, EI: 1 })
easyRoute.addNode("EI", { BX: 100, EH: 1, EJ: 100, EK: 1 })
easyRoute.addNode("EJ", { EE: 10, EI: 100, EL: 10 })
easyRoute.addNode("EK", { EI: 1, EL: 100, EM: 1 })
easyRoute.addNode("EL", { EJ: 10, EK: 100, EO: 100, GV: 100 })
easyRoute.addNode("EM", { BZ: 100, EK: 1, EN: 1 })
easyRoute.addNode("EN", { CC: 100, EM: 1, EV: 1 })
easyRoute.addNode("EO", { EL: 100, EP: 1, EV: 10 })
easyRoute.addNode("EP", { EO: 1, EQ: 10 })
easyRoute.addNode("EQ", { EP: 10, ER: 1 })
easyRoute.addNode("ER", { EQ: 1, ES: 1 })
easyRoute.addNode("ES", { CI: 100, CQ: 1, ER: 1, ET: 1 })
easyRoute.addNode("ET", { CG: 100, ES: 1, EU: 1 })
easyRoute.addNode("EU", { CF: 100, ET: 1, EW: 10 })
easyRoute.addNode("EV", { EN: 1, EO: 10, EW: 10 })
easyRoute.addNode("EW", { CD: 100, EU: 10, EV: 10 })
easyRoute.addNode("EX", { EY: 1, FL: 1, FS: 1 })
easyRoute.addNode("EY", { EX: 1, FA: 1, FB: 1 })
easyRoute.addNode("EZ", { CW: 1, FA: 1, FB: 1 })
easyRoute.addNode("FA", { EY: 1, EZ: 1, FG: 1 })
easyRoute.addNode("FB", { CZ: 1, EY: 1, EZ: 1 })
easyRoute.addNode("FC", { CV: 1, FD: 1, FF: 1 })
easyRoute.addNode("FD", { FC: 1, FE: 1 })
easyRoute.addNode("FE", { CU: 1, FD: 1 })
easyRoute.addNode("FF", { FC: 1, FG: 1, FI: 1 })
easyRoute.addNode("FG", { FA: 1, FF: 1, FH: 10, FL: 1 })
easyRoute.addNode("FH", { FG: 10, FI: 10, FK: 1 })
easyRoute.addNode("FI", { FF: 1, FH: 10, FJ: 1 })
easyRoute.addNode("FJ", { FI: 1, FK: 10, FM: 1 })
easyRoute.addNode("FK", { FH: 1, FJ: 10, FL: 1 })
easyRoute.addNode("FL", { EX: 1, FG: 1, FK: 1, FR: 1 })
easyRoute.addNode("FM", { FJ: 1, FN: 10, FP: 1 })
easyRoute.addNode("FN", { FM: 10, FO: 1 })
easyRoute.addNode("FO", { FN: 1, FP: 1, FQ: 10, FV: 1, FY: 1 })
easyRoute.addNode("FP", { FM: 1, FO: 1, GR: 1 })
easyRoute.addNode("FQ", { FO: 10, FR: 1, FU: 1 })
easyRoute.addNode("FR", { FL: 1, FQ: 1, FS: 10 })
easyRoute.addNode("FS", { EX: 1, FR: 10, FT: 1 })
easyRoute.addNode("FT", { FS: 1, FU: 100, GV: 100 })
easyRoute.addNode("FU", { FQ: 1, FT: 100, FW: 10 })
easyRoute.addNode("FV", { FO: 1, FW: 100 })
easyRoute.addNode("FW", { FU: 10, FV: 100, FX: 10, GV: 100 })
easyRoute.addNode("FX", { FW: 10, FY: 10, GS: 1 })
easyRoute.addNode("FY", { FO: 1, FX: 10, FZ: 1 })
easyRoute.addNode("FZ", { FY: 1, GO: 1, GQ: 10 })
easyRoute.addNode("GA", { DC: 100, GB: 1 })
easyRoute.addNode("GB", { DP: 10, GC: 1 })
easyRoute.addNode("GC", { DW: 1, GB: 1, GD: 10 })
easyRoute.addNode("GD", { GC: 10, GE: 1000, GW: 1 })
easyRoute.addNode("GE", { GD: 1000, GF: 1 })
easyRoute.addNode("GF", { GE: 1, GH: 100, GG: 1 })
easyRoute.addNode("GG", { GF: 1, GI: 10, GJ: 1 })
easyRoute.addNode("GH", { GF: 100, GI: 1, GW: 100 })
easyRoute.addNode("GI", { GG: 10, GH: 1, GK: 1 })
easyRoute.addNode("GJ", { GG: 1, GK: 1, GL: 1 })
easyRoute.addNode("GK", { GI: 1, GJ: 1, GL: 1, GM: 1 })
easyRoute.addNode("GL", { GJ: 1, GK: 1, GP: 1 })
easyRoute.addNode("GM", { GK: 1, GN: 10 })
easyRoute.addNode("GN", { GM: 10, GO: 10, GS: 100 })
easyRoute.addNode("GO", { FZ: 1, GN: 10, GP: 10 })
easyRoute.addNode("GP", { GL: 1, GO: 10, GQ: 1 })
easyRoute.addNode("GQ", { FZ: 10, GP: 1, GR: 1 })
easyRoute.addNode("GR", { FP: 1, GQ: 1 })
easyRoute.addNode("GS", { FX: 1, GN: 100, GT: 100 })
easyRoute.addNode("GT", { EC: 100, GS: 100, GU: 100 })
easyRoute.addNode("GU", { ED: 100, GT: 100, GV: 100 })
easyRoute.addNode("GV", { EL: 100, FT: 100, FW: 100, GU: 100 })
easyRoute.addNode("GW", { DX: 10, DZ: 1, GD: 1, GH: 10000 })

export {easyRoute};